name: DEPLOY-CLUSTER

on:
  workflow_dispatch:
    inputs:
      CLIENT:
        description: 'Client name'
        required: true
        default: 'local'
      CLUSTER:
        description: 'Cluster Name'
        required: true
        default: billi
      PULLSECRET:
        description: 'Pull Secret'
        required: true
        default: /root/openshift_pull.json
      INVENTORY:
        description: 'inventory'
        required: true
        default: .github/inventory_ci.yml

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLIENT: ${{github.event.inputs.CLIENT}}
 CLUSTER: ${{github.event.inputs.CLUSTER}}
 PULLSECRET: ${{github.event.inputs.PULLSECRET}}
 INVENTORY: ${{github.event.inputs.INVENTORY}}

jobs:
    requirements:
      runs-on: libvirt
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install ansible
         run: which ansible-playbook || yum -y install ansible
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           kcli create sushy-service
       - name: Clean up
         continue-on-error: true
         run: |
           kcli -C $CLIENT delete plan --yes $CLUSTER || true
           [ -d billi ] && rm -rf billi

    deploy-kcli-plan:
      needs: requirements
      runs-on: libvirt
      steps:
      - name: Deploy kcli plan
        run: |
          kcli -C $CLIENT create plan $CLUSTER

    deploy-billi-cluster:
      needs: deploy-kcli-plan
      runs-on: libvirt
      steps:
      - name: Deploy billi cluster
        run: |
          grep -q "^192.168.128.253 api.billi.karmalabs.corp" /etc/hosts || echo 192.168.128.253 api.billi.karmalabs.corp >> /etc/hosts
          ansible-playbook -i $INVENTORY run.yml
